[[Xorg_libICE]]
arch = "aarch64"
git-tree-sha1 = "11557c7c618dc6fada0cc28cc11b83f81bc50f7d"
libc = "musl"
os = "linux"

    [[Xorg_libICE.download]]
    sha256 = "138a62e477b4d99d08aab816e3b004306afe0a027bbf5bf7513cd4b4768d46f3"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libICE_jll.jl/releases/download/Xorg_libICE-v1.0.10+0/Xorg_libICE.v1.0.10.aarch64-linux-musl.tar.gz"
[[Xorg_libICE]]
arch = "aarch64"
git-tree-sha1 = "bf8541795961aa8cc83d7a417faf3d70a448fa08"
libc = "glibc"
os = "linux"

    [[Xorg_libICE.download]]
    sha256 = "02c3ec970cebca235d08c198a8707d1a00fc2062535298e8152e7e90ce84e5a3"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libICE_jll.jl/releases/download/Xorg_libICE-v1.0.10+0/Xorg_libICE.v1.0.10.aarch64-linux-gnu.tar.gz"
[[Xorg_libICE]]
arch = "x86_64"
git-tree-sha1 = "3d96de8fe541bf602e99bb0f5a4bce35b1cb1b0c"
libc = "glibc"
os = "linux"

    [[Xorg_libICE.download]]
    sha256 = "89b5833c125e010a90f859efccf539fb404404515e89b92a5941cf6b54749015"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libICE_jll.jl/releases/download/Xorg_libICE-v1.0.10+0/Xorg_libICE.v1.0.10.x86_64-linux-gnu.tar.gz"
[[Xorg_libICE]]
arch = "powerpc64le"
git-tree-sha1 = "64ac0af65d0097633637020b50bf3daaeb25e78a"
libc = "glibc"
os = "linux"

    [[Xorg_libICE.download]]
    sha256 = "b87fbe95dbaeb4aae45b6cfb4df54715208739f7658134ae29ef6e17af0ef069"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libICE_jll.jl/releases/download/Xorg_libICE-v1.0.10+0/Xorg_libICE.v1.0.10.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libICE]]
arch = "x86_64"
git-tree-sha1 = "ca74ad05199cd4ef3f944bd4e105d19ad4c09c43"
os = "freebsd"

    [[Xorg_libICE.download]]
    sha256 = "2d9f66d26a60c3ec96b4389d0345158140c9b092f0c9a9e6f0097a8a38e6b3f2"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libICE_jll.jl/releases/download/Xorg_libICE-v1.0.10+0/Xorg_libICE.v1.0.10.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_libICE]]
arch = "i686"
git-tree-sha1 = "a817d094ee7dc2e45a3ff7e94d778b5cc9455e10"
libc = "glibc"
os = "linux"

    [[Xorg_libICE.download]]
    sha256 = "d371930583070eb3db749ec0d3298cf84bda36997bb37dc809fad1fcbf639951"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libICE_jll.jl/releases/download/Xorg_libICE-v1.0.10+0/Xorg_libICE.v1.0.10.i686-linux-gnu.tar.gz"
[[Xorg_libICE]]
arch = "i686"
git-tree-sha1 = "2848d90f9b7e52683bc2cd605d719e2dbe584de1"
libc = "musl"
os = "linux"

    [[Xorg_libICE.download]]
    sha256 = "57b7d9eba19ec4f054a040ffc53c04d12bf029ee4b826c32db2d9c6a02384805"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libICE_jll.jl/releases/download/Xorg_libICE-v1.0.10+0/Xorg_libICE.v1.0.10.i686-linux-musl.tar.gz"
[[Xorg_libICE]]
arch = "armv7l"
git-tree-sha1 = "9b5ad35ae8325020afb7b1a7e59a28884389c9d5"
libc = "glibc"
os = "linux"

    [[Xorg_libICE.download]]
    sha256 = "6d59b8b530d808c8566a5a5ad74b7c38bffd3b5f12ba319a61b030104bda2f50"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libICE_jll.jl/releases/download/Xorg_libICE-v1.0.10+0/Xorg_libICE.v1.0.10.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libICE]]
arch = "x86_64"
git-tree-sha1 = "19038229d454c244fd3d73f46a058ea8eb8a1f8c"
libc = "musl"
os = "linux"

    [[Xorg_libICE.download]]
    sha256 = "f0afe76c15c87388f2f5959e089755c82ae4aafc34715e4fac63562262708682"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libICE_jll.jl/releases/download/Xorg_libICE-v1.0.10+0/Xorg_libICE.v1.0.10.x86_64-linux-musl.tar.gz"
[[Xorg_libICE]]
arch = "armv7l"
git-tree-sha1 = "5eeef8a839e209ce0e1aac114e746a8d7c39a981"
libc = "musl"
os = "linux"

    [[Xorg_libICE.download]]
    sha256 = "abb1da9eef85e1d71431808f5d5c1ec9775e8813ec7917a4773bdd78b6c14166"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libICE_jll.jl/releases/download/Xorg_libICE-v1.0.10+0/Xorg_libICE.v1.0.10.armv7l-linux-musleabihf.tar.gz"
